#!/usr/bin/env python3
"""
为升级物品生成 tooltip 本地化条目。

原理：Dota 2 的 tooltip 按「能力名」查找，升级物品叫 item_lv_xxx，
引擎找不到 DOTA_Tooltip_..._item_lv_xxx_* 条目，于是描述整片空白。

好消息是官方描述里的数值都是 `%sheep_duration%` 这类占位符，运行时从
该物品自己的 AbilityValues 取值。所以描述文本可以原样复制，数值会自动变成升级后的值，
不需要改一个字。

用法:
    python scripts/gen_item_localization.py            # 写入中英文两份 localization
    python scripts/gen_item_localization.py --preview  # 只看中文输出

幂等：每次先剔除已生成的 item_lv_* 条目，再重新追加。
"""

import argparse
import json
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ITEMS_TXT = os.path.join(REPO, 'pak01_dir', 'scripts', 'npc', 'items.txt')
LOC = {
    'schinese': os.path.join(REPO, 'pak01_dir', 'resource', 'localization', 'abilities_schinese.txt'),
    'english': os.path.join(REPO, 'pak01_dir', 'resource', 'localization', 'abilities_english.txt'),
}
UPGRADES = json.load(open(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                       'item_upgrades.json'), encoding='utf-8'))

MARKER_BEGIN = '\t\t// >>> BEGIN generated item upgrade tooltips <<<'
MARKER_END = '\t\t// <<< END generated item upgrade tooltips >>>'

# 升级物品的专属 Lore：保留原版 flavor text，尾部追加一句淬炼说明。
# 已核对：原版 Lore 中英文各 45 条，全部以句号结尾，直接拼接即可。
LORE_SUFFIX = {
    'schinese': '经由更高层次的技艺淬炼后，它的力量已远非昔日可比。',
    'english': ' Tempered by higher craftsmanship, its power now far exceeds the original.',
}
# 少数中立物品本来就没有 Lore（hydras_breath / nullifier / trident），用独立文案兜底
LORE_FALLBACK = {
    'schinese': '经由更高层次的技艺淬炼而成，它的力量已远非昔日可比。',
    'english': 'Tempered by higher craftsmanship, its power far exceeds the original.',
}

# 三叉戟新增字段沿用官方同类属性标签，避免硬编码中英文文案。
EXTRA_TOOLTIP_SOURCES = {
    'item_trident': {
        'slow_resistance': ('item_sange', 'slow_resistance'),
        'manacost_reduction': ('item_kaya_and_sange', 'manacost_reduction'),
        'cast_speed_pct': ('item_yasha_and_kaya', 'cast_speed_pct'),
    },
}


def item_names():
    txt = open(ITEMS_TXT, encoding='utf-8-sig', errors='replace').read()
    return set(re.findall(r'^\t"(item_[a-z0-9_]+)"\s*$', txt, re.M))


def split_token(tok, names):
    """把 item_dagon_5_Description 拆成 (item_dagon_5, Description)。
    从长到短匹配，避免 item_dagon 抢走 item_dagon_5 的条目。"""
    for i in range(len(tok), 0, -1):
        if tok[:i] in names:
            return tok[:i], tok[i + 1:]
    return None, None


def collect(src, names):
    """{物品名: {后缀: 值}}，后缀为 '' 表示物品名条目"""
    out = {}
    for line in src.split('\n'):
        m = re.match(r'^\s*"(DOTA_Tooltip_[Aa]bility_item_[A-Za-z0-9_:]+)"\s+"(.*)"\s*$', line)
        if not m:
            continue
        key, val = m.group(1), m.group(2)
        n, suffix = split_token('item_' + key.split('item_', 1)[1], names)
        tooltip_sources = {source for mapping in EXTRA_TOOLTIP_SOURCES.values()
                           for source, _ in mapping.values()}
        if n in UPGRADES or n in tooltip_sources:
            out.setdefault(n, {})[suffix or ''] = val
        # 配方名也要，用来生成 item_recipe_lv_xxx
        if n and n.startswith('item_recipe_') and n[len('item_recipe_'):] in UPGRADES:
            out.setdefault(n, {})[suffix or ''] = val
    return out


def upgrade_name(orig, lang):
    if lang == 'schinese':
        return orig + '·升级'
    return 'Upgraded ' + orig


def build_block(entries, lang):
    lines = [MARKER_BEGIN,
             '\t\t// Generated by scripts/gen_item_localization.py — do not edit by hand.',
             '']
    for name in sorted(UPGRADES):
        got = entries.get(name)
        if not got:
            print('  ! %s 没有可复制的 tooltip 条目，跳过' % name, file=sys.stderr)
            continue
        got = dict(got)
        for suffix, (source_name, source_suffix) in EXTRA_TOOLTIP_SOURCES.get(name, {}).items():
            source = entries.get(source_name, {})
            if suffix not in got and source_suffix in source:
                got[suffix] = source[source_suffix]

        short = name[5:]
        base = got.get('', short)
        new_name = upgrade_name(base, lang)

        lines.append('\t\t// %s' % name)
        lines.append('\t\t"DOTA_Tooltip_Ability_item_lv_%s"\t\t"%s"' % (short, new_name))
        lines.append('\t\t"DOTA_Tooltip_Ability_item_recipe_lv_%s"\t\t"%s"'
                     % (short, (new_name + '配方') if lang == 'schinese' else (new_name + ' Recipe')))

        for suffix in sorted(k for k in got if k):
            val = got[suffix]
            if suffix == 'Lore':
                val = (val + LORE_SUFFIX[lang]) if val else LORE_FALLBACK[lang]
            lines.append('\t\t"DOTA_Tooltip_ability_item_lv_%s_%s"\t\t"%s"'
                         % (short, suffix, val))
        # 原物品没有 Lore 的（中立物品），补一条淬炼文案
        if 'Lore' not in got:
            lines.append('\t\t"DOTA_Tooltip_ability_item_lv_%s_Lore"\t\t"%s"'
                         % (short, LORE_FALLBACK[lang]))
        lines.append('')
    lines.append(MARKER_END)
    return lines


def strip_previous(src):
    """剔除上一次生成的区块，保证幂等"""
    if MARKER_BEGIN not in src:
        return src
    out, keep = [], True
    for line in src.split('\n'):
        if line.strip() == MARKER_BEGIN.strip():
            keep = False
            continue
        if line.strip() == MARKER_END.strip():
            keep = True
            continue
        if keep:
            out.append(line)
    return '\n'.join(out)


def process(path, lang, preview=False):
    src = open(path, encoding='utf-8-sig', errors='replace').read()
    src = strip_previous(src)
    names = item_names()
    entries = collect(src, names)
    block = build_block(entries, lang)

    # 必须插到 "Tokens" 块内部。
    # 曾经这里写的是「找最后一个 }」，但最后一个 } 是 lang 的闭合而不是 Tokens 的，
    # 结果条目落在 Tokens 之外、游戏根本不加载 —— 物品名和描述全空。
    m = re.search(r'^[ \t]*"Tokens"[ \t]*$', src, re.M)
    if not m:
        sys.exit('无法在 %s 中定位 Tokens 块' % path)
    depth, end = 0, None
    for i in range(m.end(), len(src)):
        if src[i] == '{':
            depth += 1
        elif src[i] == '}':
            depth -= 1
            if depth == 0:
                end = i
                break
    if end is None:
        sys.exit('Tokens 块括号不配对：%s' % path)
    new = (src[:end].rstrip('\n') + '\n\n' + '\n'.join(block) + '\n'
           + src[end:])

    if preview:
        print('\n'.join(block))
        return
    with open(path, 'w', encoding='utf-8-sig', newline='') as f:
        f.write(new)
    print('已更新 %s（%d 个升级物品）' % (os.path.relpath(path, REPO), len(UPGRADES)))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--preview', action='store_true', help='只打印中文结果，不写文件')
    ap.add_argument('--lang', choices=['schinese', 'english', 'all'], default='all')
    args = ap.parse_args()
    if args.preview:
        process(LOC['schinese'], 'schinese', preview=True)
        return
    langs = ['schinese', 'english'] if args.lang == 'all' else [args.lang]
    for lang in langs:
        process(LOC[lang], lang)


if __name__ == '__main__':
    main()
